import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const poppins = Geist({
  variable: "--font-poppins",
  subsets: ["latin"],
});

const poppinsMono = Geist_Mono({
  variable: "--font-poppins-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${poppinsMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div>{children}</div>
      </body>
    </html>
  );
}
